/-
Copyright (c) 2026 Kuldeep S. Meel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kuldeep S. Meel
-/
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Fintype.Pi
import Mathlib.Algebra.BigOperators.Group.Finset

/-!
# Atoms of a finite family of sets

Given a finite family of subsets `A : ι → Finset Ω` of a finite type `Ω`, the *atoms*
generated by the family are the (at most `2 ^ |ι|`) sets of the form `⋂ⱼ Cⱼ`, where each
`Cⱼ` is either `A j` or its complement.  They are indexed by *sign vectors* `s : ι → Bool`,
with `s j = true` meaning "take `A j`" and `s j = false` meaning "take the complement".

The main content of this file is that the atoms form a partition of `Ω` refining every
member of the family:

* `atom`, `signOf` — the atoms and the sign vector of a point;
* `mem_atom_iff`, `mem_atom_signOf` — membership in an atom is exactly "has this sign vector";
* `atom_disjoint` — distinct sign vectors give disjoint atoms;
* `atom_biUnion_univ` — the atoms cover `Ω`;
* `sum_card_atom` — hence their cardinalities sum to `|Ω|`;
* `member_eq_biUnion_atom` — every `A j` is the union of the atoms selecting it;
* `sum_card_atom_inter` — the counting form `∑ₛ |S ∩ atom A s| = |S|`, valid for *any* `S`,
  which is the shape used by lower-bound arguments.

No `sorry`.
-/

open scoped BigOperators

open Finset

namespace Arlib

/-- The atom of the family `A` with sign vector `s`: the points that lie in `A j`
for exactly those `j` with `s j = true`. -/
def atom {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]
    (A : ι → Finset Ω) (s : ι → Bool) : Finset Ω :=
  Finset.univ.filter (fun x => ∀ j, decide (x ∈ A j) = s j)

/-- The sign vector of a point: which sets of the family it belongs to. -/
def signOf {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]
    (A : ι → Finset Ω) (x : Ω) : ι → Bool := fun j => decide (x ∈ A j)

/-- A point lies in the atom `atom A s` exactly when its sign vector is `s`. -/
theorem mem_atom_iff {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]
    (A : ι → Finset Ω) (s : ι → Bool) (x : Ω) :
    x ∈ atom A s ↔ signOf A x = s := by
  simp [atom, signOf, funext_iff]

/-- Every point lies in the atom given by its own sign vector. -/
theorem mem_atom_signOf {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]
    (A : ι → Finset Ω) (x : Ω) : x ∈ atom A (signOf A x) :=
  (mem_atom_iff A (signOf A x) x).mpr rfl

/-- **Atoms are pairwise disjoint.** -/
theorem atom_disjoint {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]
    (A : ι → Finset Ω) {s t : ι → Bool} (h : s ≠ t) :
    Disjoint (atom A s) (atom A t) := by
  rw [Finset.disjoint_left]
  intro x hs ht
  exact h (((mem_atom_iff A s x).mp hs).symm.trans ((mem_atom_iff A t x).mp ht))

/-- **Atoms cover the space.** -/
theorem atom_biUnion_univ {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]
    (A : ι → Finset Ω) :
    (Finset.univ : Finset (ι → Bool)).biUnion (atom A) = Finset.univ := by
  refine Finset.eq_univ_iff_forall.mpr fun x => ?_
  exact Finset.mem_biUnion.mpr ⟨signOf A x, Finset.mem_univ _, mem_atom_signOf A x⟩

/-- Intersecting an arbitrary set with an atom is the same as taking the fibre of the
sign-vector map over that atom's sign vector. -/
private theorem inter_atom_eq_filter {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι]
    [DecidableEq ι] (A : ι → Finset Ω) (S : Finset Ω) (s : ι → Bool) :
    S ∩ atom A s = S.filter (fun x => signOf A x = s) := by
  ext x
  simp [Finset.mem_inter, Finset.mem_filter, mem_atom_iff]

/-- **Atoms partition the space**: their cardinalities sum to `|Ω|`. -/
theorem sum_card_atom {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]
    (A : ι → Finset Ω) :
    ∑ s : ι → Bool, (atom A s).card = Fintype.card Ω := by
  have hcard : ((Finset.univ : Finset (ι → Bool)).biUnion (atom A)).card
      = ∑ s : ι → Bool, (atom A s).card :=
    Finset.card_biUnion fun s _ t _ hst => atom_disjoint A hst
  rw [← hcard, atom_biUnion_univ, Finset.card_univ]

/-- Each member of the family is the union of the atoms whose sign vector selects it. -/
theorem member_eq_biUnion_atom {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι]
    [DecidableEq ι] (A : ι → Finset Ω) (j : ι) :
    A j = ((Finset.univ : Finset (ι → Bool)).filter (fun s => s j = true)).biUnion (atom A) := by
  ext x
  simp only [Finset.mem_biUnion, Finset.mem_filter, Finset.mem_univ, true_and, mem_atom_iff]
  constructor
  · intro hx
    exact ⟨signOf A x, by simpa [signOf] using hx, rfl⟩
  · rintro ⟨s, hs, rfl⟩
    simpa [signOf] using hs

/-- More generally, any set that is a union of atoms decomposes as a sum over atoms.
This is the counting form used by lower-bound arguments. -/
theorem sum_card_atom_inter {ι Ω : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι]
    [DecidableEq ι] (A : ι → Finset Ω) (S : Finset Ω) :
    ∑ s : ι → Bool, (S ∩ atom A s).card = S.card := by
  rw [Finset.card_eq_sum_card_fiberwise
    (f := signOf A) (s := S) (t := (Finset.univ : Finset (ι → Bool)))
    (fun x _ => Finset.mem_univ _)]
  exact Finset.sum_congr rfl fun s _ => by rw [inter_atom_eq_filter]

end Arlib
