/-
Copyright (c) 2026 Suguman Bansal. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Suguman Bansal
-/
/-
# Conditional expectation of a centred fresh draw

The measure-theoretic core of *"a sampled target is unbiased"*.

Fix a probability space, a sub-σ-algebra `m ≤ m0` thought of as "the history",
a finite type `S`, and a draw `X : Ω → S` **independent of `m`** — the fresh
randomness used at the current step.  Let `p : S → ℝ` be the law of `X` and let
each `f s' : Ω → ℝ` be a bounded `m`-measurable factor — a quantity computed
from the history alone.  Then the centred combination

    ∑_{s'} ( 1{X = s'} − p s' ) · f s'

has conditional mean zero given `m`.  Equivalently: estimating the average
`∑_{s'} p s' · f s'` by the single sample `f (X)` incurs no bias.

That is the whole content of this module, and it is proved over an *arbitrary*
space, sub-σ-algebra, finite draw space and factors — the concrete process
supplying `X`, `p` and the filtration is irrelevant, which is what makes the
statement reusable across stochastic-approximation schemes.

## Main statements

* `integrable_of_bounded`, `integrable_sq_of_bounded` — a bounded strongly
  measurable function, and its square, are integrable on a finite measure.
* `condexp_indep_indicator`, `condexp_centred_draw_eq_zero` — **the crux**, at a
  single `s'`: a centred fresh-draw indicator has conditional mean zero, and
  stays so after multiplication by a bounded `m`-measurable factor.
* `condexp_fresh_draw_eq_zero` — the crux summed over `S`.
* `condexp_sq_le_one` — a pointwise bound survives conditioning, giving the
  second-moment bound `E[ε² ∣ m] ≤ 1`.
* `sum_inv_sq_le` — `∑_{k<n} 1/(k+1)² ≤ 2`, uniformly in `n`: the square-summable
  half of the Robbins–Monro conditions for the harmonic schedule.

See `Arlib.Probability.RobbinsMonro` and
`Arlib.Probability.StochasticApproximation` for what consumes these.
-/
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Real
import Mathlib.Probability.ConditionalExpectation

namespace Arlib.Probability

open MeasureTheory ProbabilityTheory Finset
open scoped BigOperators

/-! ## Integrability of bounded functions -/

section Integrability

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsFiniteMeasure μ]

/-- **A bounded strongly measurable function is integrable** on a finite measure. -/
theorem integrable_of_bounded {g : Ω → ℝ} {C : ℝ} (hg : StronglyMeasurable g)
    (hb : ∀ ω, |g ω| ≤ C) : Integrable g μ :=
  (integrable_const C).mono' hg.aestronglyMeasurable
    (Filter.Eventually.of_forall fun ω => by simpa [Real.norm_eq_abs] using hb ω)

/-- **The square of a bounded strongly measurable function is integrable.**

The typical use is a noise term known to satisfy `|ε| ≤ 1` pointwise, whose
square must be shown integrable before any second-moment argument. -/
theorem integrable_sq_of_bounded {g : Ω → ℝ} (hg : StronglyMeasurable g)
    (hb : ∀ ω, |g ω| ≤ 1) : Integrable (fun ω => (g ω) ^ 2) μ := by
  refine integrable_of_bounded (C := 1) (hg.pow 2) fun ω => ?_
  rw [abs_pow, ← one_pow 2]
  exact pow_le_pow_left₀ (abs_nonneg _) (hb ω) 2

end Integrability

/-! ## The crux: a fresh draw has conditional mean zero

Throughout, `m` is the "past" σ-algebra, `m0` the ambient one, and `X` the draw
made *now*.  Independence is stated as `Indep (MeasurableSpace.comap X _) m μ`,
i.e. "the draw is independent of the past"; `ProbabilityTheory.Indep.symm`
converts from the other argument order if a caller has it that way round. -/

section FreshDraw

variable {Ω S : Type*} [MeasurableSpace S] [MeasurableSingletonClass S] [DecidableEq S]
  {m m0 : MeasurableSpace Ω} {μ : Measure Ω} [IsProbabilityMeasure μ]
  {X : Ω → S}

/-- The indicator of `{X = s'}` is measurable for the σ-algebra generated by `X`. -/
theorem stronglyMeasurable_comap_indicator (s' : S) :
    StronglyMeasurable[MeasurableSpace.comap X inferInstance]
      (fun ω => if X ω = s' then (1 : ℝ) else 0) := by
  have hXm : Measurable[MeasurableSpace.comap X inferInstance] X :=
    Measurable.of_comap_le le_rfl
  refine Measurable.stronglyMeasurable ?_
  exact (measurable_const.ite (hXm (measurableSet_singleton s')) measurable_const)

omit [IsProbabilityMeasure μ] in
/-- **The mean of a fresh-draw indicator is its law.** -/
theorem integral_indicator_draw (hX : Measurable X) (s' : S) :
    ∫ ω, (if X ω = s' then (1 : ℝ) else 0) ∂μ = (μ {ω | X ω = s'}).toReal := by
  have hset : MeasurableSet {ω | X ω = s'} := hX (measurableSet_singleton s')
  have : (fun ω => if X ω = s' then (1 : ℝ) else 0)
      = Set.indicator {ω | X ω = s'} (fun _ => (1 : ℝ)) := by
    funext ω; by_cases h : X ω = s' <;> simp [Set.indicator, h, Set.mem_setOf_eq]
  rw [this, integral_indicator_const _ hset, smul_eq_mul, mul_one]

/-- **A fresh-draw indicator is conditionally deterministic.**

If `X` is independent of the past `m`, then `E[1{X = s'} ∣ m]` is the constant
`P(X = s')`, almost surely.  This is `condexp_indep_eq` specialised to the
indicator, with the resulting integral evaluated. -/
theorem condexp_indep_indicator (hm : m ≤ m0) (hX : Measurable X)
    (hindep : Indep (MeasurableSpace.comap X inferInstance) m μ) (s' : S) :
    μ[fun ω => (if X ω = s' then (1 : ℝ) else 0)|m]
      =ᵐ[μ] fun _ => (μ {ω | X ω = s'}).toReal := by
  have h := condexp_indep_eq (hX.comap_le) hm (stronglyMeasurable_comap_indicator s') hindep
  refine h.trans ?_
  rw [integral_indicator_draw hX s']

/-- **The crux, at a single draw value.**

Let `X` be a draw independent of the past `m`, with `P(X = s') = p`, and let `f`
be a bounded `m`-measurable factor — a function of the past.  Then the centred
indicator, tested against `f`, has conditional mean zero:

    E[ (1{X = s'} − p) · f ∣ m ] = 0   a.s.

The `m`-measurable factor is pulled out with `condexp_stronglyMeasurable_mul`,
and what is left is `E[1{X = s'} ∣ m] − p = p − p = 0` by
`condexp_indep_indicator`.  Every integrability side condition is discharged by
boundedness on a probability measure. -/
theorem condexp_centred_draw_eq_zero (hm : m ≤ m0) (hX : Measurable X)
    (hindep : Indep (MeasurableSpace.comap X inferInstance) m μ)
    {f : Ω → ℝ} (hf : StronglyMeasurable[m] f) (hfb : ∀ ω, |f ω| ≤ 1)
    {p : ℝ} {s' : S} (hp : (μ {ω | X ω = s'}).toReal = p) :
    μ[fun ω => ((if X ω = s' then (1 : ℝ) else 0) - p) * f ω|m] =ᵐ[μ] 0 := by
  set g : Ω → ℝ := fun ω => (if X ω = s' then (1 : ℝ) else 0) - p with hg_def
  -- `f` is measurable for the ambient σ-algebra too.
  have hf0 : StronglyMeasurable f := hf.mono hm
  -- Bounds.
  have hgb : ∀ ω, |g ω| ≤ 1 + |p| := fun ω => by
    have h1 : |(if X ω = s' then (1 : ℝ) else 0)| ≤ 1 := by
      by_cases h : X ω = s' <;> simp [h]
    calc |g ω| ≤ |(if X ω = s' then (1 : ℝ) else 0)| + |p| := abs_sub _ _
      _ ≤ 1 + |p| := by linarith
  have hgm : StronglyMeasurable g :=
    ((stronglyMeasurable_comap_indicator s').mono hX.comap_le).sub stronglyMeasurable_const
  have hgi : Integrable g μ := integrable_of_bounded hgm hgb
  have hfgi : Integrable (f * g) μ := by
    refine integrable_of_bounded (C := 1 + |p|) (hf0.mul hgm) fun ω => ?_
    rw [Pi.mul_apply, abs_mul]
    calc |f ω| * |g ω| ≤ 1 * (1 + |p|) :=
          mul_le_mul (hfb ω) (hgb ω) (abs_nonneg _) zero_le_one
      _ = 1 + |p| := one_mul _
  -- Pull the past-measurable factor out.
  have hpull : μ[f * g|m] =ᵐ[μ] f * μ[g|m] := condexp_stronglyMeasurable_mul hf hfgi hgi
  -- The remaining conditional expectation is `p - p = 0`.
  have hzero : μ[g|m] =ᵐ[μ] 0 := by
    have hsub : μ[g|m] =ᵐ[μ] μ[fun ω => (if X ω = s' then (1 : ℝ) else 0)|m]
        - μ[fun _ : Ω => p|m] := by
      have := condexp_sub (μ := μ) (m := m)
        (integrable_of_bounded (C := 1) ((stronglyMeasurable_comap_indicator s').mono hX.comap_le)
          (fun ω => by by_cases h : X ω = s' <;> simp [h]))
        (integrable_const p)
      exact this
    have hconst : μ[fun _ : Ω => p|m] = fun _ => p := condexp_const hm p
    filter_upwards [hsub, condexp_indep_indicator hm hX hindep s'] with ω h1 h2
    simp only [Pi.sub_apply, hconst] at h1
    rw [h1, h2, hp, sub_self]
    rfl
  -- Assemble.
  have hcomm : (fun ω => ((if X ω = s' then (1 : ℝ) else 0) - p) * f ω) = f * g := by
    funext ω; simp [hg_def, Pi.mul_apply, mul_comm]
  rw [hcomm]
  refine hpull.trans ?_
  filter_upwards [hzero] with ω hω
  simp [Pi.mul_apply, hω]

variable [Fintype S]

/-- **The `err_mean` field, abstractly: a fresh draw has conditional mean zero.**

If `X : Ω → S` is a draw on a finite space, independent of the past `m`, with law
`p`, and each `f s'` is a bounded `m`-measurable factor, then

    E[ ∑_{s'} (1{X = s'} − p s') · f s' ∣ m ] = 0   a.s.

This is the *unbiasedness of a sampled target*: it is the shape into which the
noise of any scheme that estimates `∑_{s'} p s' · f s'` by the single sample
`f (X)` decomposes.  The proof is `condexp_finset_sum` to push the conditioning
inside the (finite) sum, then `condexp_centred_draw_eq_zero` termwise. -/
theorem condexp_fresh_draw_eq_zero (hm : m ≤ m0) (hX : Measurable X)
    (hindep : Indep (MeasurableSpace.comap X inferInstance) m μ)
    {p : S → ℝ} {f : S → Ω → ℝ}
    (hlaw : ∀ s', (μ {ω | X ω = s'}).toReal = p s')
    (hf : ∀ s', StronglyMeasurable[m] (f s'))
    (hfb : ∀ s' ω, |f s' ω| ≤ 1) :
    μ[fun ω => ∑ s' : S, ((if X ω = s' then (1 : ℝ) else 0) - p s') * f s' ω|m] =ᵐ[μ] 0 := by
  set F : S → Ω → ℝ :=
    fun s' ω => ((if X ω = s' then (1 : ℝ) else 0) - p s') * f s' ω with hF_def
  have hFi : ∀ s' ∈ (univ : Finset S), Integrable (F s') μ := by
    intro s' _
    refine integrable_of_bounded (C := (1 + |p s'|) * 1) ?_ ?_
    · refine StronglyMeasurable.mul ?_ ((hf s').mono hm)
      exact ((stronglyMeasurable_comap_indicator s').mono hX.comap_le).sub stronglyMeasurable_const
    · intro ω
      rw [hF_def, abs_mul]
      have h1 : |(if X ω = s' then (1 : ℝ) else 0) - p s'| ≤ 1 + |p s'| := by
        have : |(if X ω = s' then (1 : ℝ) else 0)| ≤ 1 := by
          by_cases h : X ω = s' <;> simp [h]
        calc |(if X ω = s' then (1 : ℝ) else 0) - p s'|
            ≤ |(if X ω = s' then (1 : ℝ) else 0)| + |p s'| := abs_sub _ _
          _ ≤ 1 + |p s'| := by linarith
      exact mul_le_mul h1 (hfb s' ω) (abs_nonneg _) (by positivity)
  have hsum : (fun ω => ∑ s' : S, F s' ω) = ∑ s' ∈ (univ : Finset S), F s' := by
    funext ω; simp
  rw [hsum]
  refine (condexp_finset_sum hFi).trans ?_
  have hterm : ∀ s' ∈ (univ : Finset S), μ[F s'|m] =ᵐ[μ] (0 : Ω → ℝ) := fun s' _ =>
    condexp_centred_draw_eq_zero hm hX hindep (hf s') (hfb s') (hlaw s')
  have := eventuallyEq_sum (s := (univ : Finset S)) (f := fun s' => μ[F s'|m])
    (g := fun _ => (0 : Ω → ℝ)) hterm
  refine this.trans ?_
  filter_upwards with ω
  simp

end FreshDraw

/-! ## A pointwise bound survives conditioning -/

section SecondMoment

variable {Ω : Type*} {m m0 : MeasurableSpace Ω} {μ : Measure Ω} [IsProbabilityMeasure μ]

/-- **The `err_second` field, abstractly, with `B = 1`.**

If `|g| ≤ 1` pointwise then `E[g² ∣ m] ≤ 1` almost surely.  Being a pointwise
bound, `g² ≤ 1` passes through `condexp_mono` against the constant `1`, whose
conditional expectation is itself (`condexp_const`). -/
theorem condexp_sq_le_one (hm : m ≤ m0) {g : Ω → ℝ} (hg : StronglyMeasurable g)
    (hb : ∀ ω, |g ω| ≤ 1) : μ[fun ω => (g ω) ^ 2|m] ≤ᵐ[μ] fun _ => 1 := by
  have hle : (fun ω => (g ω) ^ 2) ≤ᵐ[μ] fun _ : Ω => (1 : ℝ) := by
    filter_upwards with ω
    have : |g ω| ^ 2 ≤ 1 ^ 2 := pow_le_pow_left₀ (abs_nonneg _) (hb ω) 2
    simpa [abs_pow, sq_abs] using this
  have := condexp_mono (m := m) (integrable_sq_of_bounded hg hb) (integrable_const (1 : ℝ)) hle
  rwa [condexp_const hm (1 : ℝ)] at this

end SecondMoment

/-! ## The harmonic schedule is square-summable, with an explicit constant -/

/-- The sharpened, telescoping form: `∑_{k<n} 1/(k+1)² ≤ 2 − 2/(n+1)`.

The step needs `1/(n+1)² ≤ 2/(n+1) − 2/(n+2) = 2/((n+1)(n+2))`, i.e.
`(n+1)(n+2) ≤ 2(n+1)²`, which is `n ≥ 0`. -/
theorem sum_inv_sq_le_aux (n : ℕ) :
    ∑ k ∈ Finset.range n, (1 / ((k : ℝ) + 1)) ^ 2 ≤ 2 - 2 / ((n : ℝ) + 1) := by
  induction n with
  | zero => norm_num
  | succ n ih =>
      rw [Finset.sum_range_succ]
      have hn : (0 : ℝ) < (n : ℝ) + 1 := by positivity
      have hn2 : (0 : ℝ) < (n : ℝ) + 2 := by positivity
      have key : (1 / ((n : ℝ) + 1)) ^ 2 ≤ 2 / ((n : ℝ) + 1) - 2 / ((n : ℝ) + 2) := by
        rw [div_pow, one_pow, div_sub_div _ _ (ne_of_gt hn) (ne_of_gt hn2),
          div_le_div_iff₀ (by positivity) (by positivity)]
        nlinarith [sq_nonneg ((n : ℝ)), sq_nonneg ((n : ℝ) + 1)]
      have hcast : ((n + 1 : ℕ) : ℝ) + 1 = (n : ℝ) + 2 := by push_cast; ring
      rw [hcast]
      linarith

/-- **`∑_{k<n} 1/(k+1)² ≤ 2`, uniformly in `n`.**

The harmonic schedule `α_k = 1/(k+1)` therefore satisfies the square-summability
half of the Robbins–Monro conditions with the uniform constant `C = 2`, while
`Arlib.StochApprox.tendsto_sum_atTop_of_count_harmonic_le` supplies the
divergent half. -/
theorem sum_inv_sq_le (n : ℕ) : ∑ k ∈ Finset.range n, (1 / ((k : ℝ) + 1)) ^ 2 ≤ 2 := by
  have h : (0 : ℝ) ≤ 2 / ((n : ℝ) + 1) := by positivity
  linarith [sum_inv_sq_le_aux n]

end Arlib.Probability
